name = "pos-app"
compatibility_date = "2026-01-31"
compatibility_flags = ["nodejs_compat"]

main = "_worker.js"

[build]
command = "npm run build"

[env.production]
vars = { NODE_ENV = "production" }
